workspace:
  base: /go
  path: src/github.com/WellMafra/drone-demo

pipeline:
  build:
    image: instrumentisto/dep:0.4.1-alpine
    commands:
      - dep ensure
      - go test ./...
      - go build

#  publish:
#    image: plugins/docker
#    repo: wellmafra/drone-demo
#    tags: [ 1, 1.1, latest ]
#    registry: index.docker.io

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone